name:                storm
version:             0.1.0.0
github:              "githubuser/storm"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: test

dependencies:
- base >= 4.7 && < 5
- aeson 
- lens
- lens-aeson
- attoparsec
- bytestring 
- conduit 
- mtl 
- network 
- text 
- transformers 
- containers
- fgl 
- sqlite-simple
- directory

library:
  source-dirs: src

executables:
  storm:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - storm

tests:
  storm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - storm
